"""Initial migration

Revision ID: bae98bb998c2
Revises: 
Create Date: 2025-04-25 14:26:28.389331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bae98bb998c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer')
    op.drop_table('rates_order_delivery')
    op.drop_table('selects')
    op.drop_table('associated_with')
    op.drop_table('sells')
    op.drop_table('cart')
    op.drop_table('customer')
    op.drop_table('product_feedback')
    op.drop_table('admin_views')
    op.drop_table('seller')
    op.drop_table('orders')
    op.drop_table('delivery_boy')
    op.drop_table('category')
    op.drop_table('admin')
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('pid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pname', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('unit', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('catid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['aid'], ['admin.aid'], name='product_ibfk_2', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['catid'], ['category.catid'], name='product_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('pid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('admin',
    sa.Column('aid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('apassword', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('aid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('category',
    sa.Column('catid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('catname', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('catid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('delivery_boy',
    sa.Column('did', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('dphno', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('aid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['aid'], ['admin.aid'], name='delivery_boy_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('did'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orders',
    sa.Column('oid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('paymode', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('odate', sa.DATE(), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('did', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['customer.cid'], name='orders_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['did'], ['delivery_boy.did'], name='orders_ibfk_2'),
    sa.PrimaryKeyConstraint('oid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('seller',
    sa.Column('sid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('semail', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('sphno', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('aid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['aid'], ['admin.aid'], name='seller_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('admin_views',
    sa.Column('aid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['aid'], ['admin.aid'], name='admin_views_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pid'], ['product.pid'], name='admin_views_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('aid', 'pid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('product_feedback',
    sa.Column('cid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stars', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['customer.cid'], name='product_feedback_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pid'], ['product.pid'], name='product_feedback_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cid', 'pid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('customer',
    sa.Column('cid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('cemail', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('cphno', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('cpassword', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('cid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cart',
    sa.Column('cid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ofid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['customer.cid'], name='cart_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ofid'], ['offer.ofid'], name='cart_ibfk_3'),
    sa.ForeignKeyConstraint(['pid'], ['product.pid'], name='cart_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cid', 'pid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sells',
    sa.Column('sid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pid'], ['product.pid'], name='sells_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sid'], ['seller.sid'], name='sells_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sid', 'pid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('associated_with',
    sa.Column('cid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cid'], ['customer.cid'], name='associated_with_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sid'], ['seller.sid'], name='associated_with_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cid', 'sid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('selects',
    sa.Column('oid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['oid'], ['orders.oid'], name='selects_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pid'], ['product.pid'], name='selects_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('oid', 'pid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rates_order_delivery',
    sa.Column('oid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('did', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stars', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['did'], ['delivery_boy.did'], name='rates_order_delivery_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['oid'], ['orders.oid'], name='rates_order_delivery_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('oid', 'did'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('offer',
    sa.Column('ofid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ofname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('minamount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('discount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('maxdiscount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ofid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
